export const FILE_TABLE_HEADERS = {
  ValidityStart: 'Fecha inicio',
  ValidityEnd: 'Fecha fin',
  ValidityStartHour: 'Hora inicio',
  ValidityEndHour: 'Hora fin',
  IndustrialShed: 'Nave',
  DestinyClient: 'Destino cliente',
  Product: 'Producto',
  Format: 'Formato',
  NumAgreement: 'Número de contrato',
  OC: 'OC',
  NumAgris: 'Num. Agris',
  DestinyDirection: 'Dirección de destino',
  Driver_RUT: 'RUT chofer',
  Driver_Name: 'Nombre chofer',
  Driver_LastName: 'Apellido chofer',
  Driver_Telephone: 'Telefono chofer',
  Patent: 'Patente',
};
