export const ERRORS_REQUESTS_MASSIVE = {
  NULL: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.NULL',
  INVALID_DATE: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.INVALID_DATE',
  START_DATE: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.START_DATE',
  START_DATE_HOUR: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.START_DATE_HOUR',
  END_DATE_TODAY: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.END_DATE_TODAY',
  RUT: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.RUT',
  RUT_INVALID: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.RUT_INVALID',
  RUT_REPEAT: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.RUT_REPEAT',
  PATENT: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.PATENT',
  PATENT_INVALID: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.PATENT_INVALID',
  PATENT_REPEAT: 'REQUEST_NEW.UPLOAD.TABLE_ERRORS.PATENT_REPEAT',
};
