export const TOOLTIPS = {
  ADD: 'add',
  DETAIL: 'remove_red_eye',
  SEARCH: 'search',
  REMOVE: 'delete',
  EDIT: 'edit',
  ACCESS_TIME: 'access_time',
  FILTER: 'icon icon-filter',
  AUTORENEW: 'autorenew',
  DONUT: 'donut_large',
  EXCEL_UPLOAD: 'insert_drive_file',
  EXCEL_DOWNLOAD: 'download_drive_file',
  PRINT: 'print',
  INFORMATION: 'info',
  CHECK: 'check',
};
