export const FORM_TITLES = {
  CREATE: 'REQUEST_NEW.REQUEST_BASIC_DATA.TITLES.TITLE_NEW',
  DETAIL: 'REQUEST_NEW.REQUEST_BASIC_DATA.TITLES.TITLE_DETAIL',
  EDIT: 'REQUEST_NEW.REQUEST_BASIC_DATA.TITLES.TITLE_EDIT',
};
