export const FORM_BUTTONS = {
  CONFIRM: 'REQUEST_NEW.REQUEST_BASIC_DATA.BUTTONS.CONFIRM',
  REFRESH: 'REQUEST_NEW.REQUEST_BASIC_DATA.BUTTONS.REFRESH',
  BACK: 'REQUEST_NEW.REQUEST_BASIC_DATA.BUTTONS.BACK',
};
