export const ERROR_HTTP_KEYS = {
  REPEATED_RUT: 'REPEATED RUT',
  REPEATED_PATENT: 'REPEATED PATENT',
  KEY_ALREADY_USED: 'KEY ALREADY USED',
  LOGIN_ALREADY_USED: 'REPEATED LOGIN',
  ITEM_NOT_IN_DB: 'ITEM NOT IN DB',
  ACC_BLOQUED: 'ACC BLOQUED',
};
