export const CLIENT_PERMISSION = 'CLIENT';
export const FROW_READER_PERMISSION = 'FROWARD_READER';

export enum PERMISSION_TYPES {
  CLIENT = 'CLIENT',
  F_READER = 'FROWARD_READER',
  F_ADMIN = 'FROWARD_ADMIN',
  F_SUPERVISOR = 'FROWARD_SUPERVISOR',
}

export const PERMISSIONS = {
  SCHEDULE: {
    CREATE: 'SCHEDULE_CREATE',
    READ: 'SCHEDULE_READ',
    UPDATE: 'SCHEDULE_UPDATE',
    DELETE: 'SCHEDULE_DELETE',
  },
  REQUEST: {
    CREATE: 'REQUEST_CREATE',
    READ: 'REQUEST_READ',
    UPDATE: 'REQUEST_UPDATE',
    DELETE: 'REQUEST_DELETE',
    FILTER: 'REQUEST_FILTER',
  },
  VEHICLE: {
    CREATE: 'VEHICLE_CREATE',
    READ: 'VEHICLE_READ',
    UPDATE: 'VEHICLE_UPDATE',
    DELETE: 'VEHICLE_DELETE',
  },
  DRIVER: {
    CREATE: 'DRIVER_CREATE',
    READ: 'DRIVER_READ',
    UPDATE: 'DRIVER_UPDATE',
    DELETE: 'DRIVER_DELETE',
  },
  CLIENT: {
    CREATE: 'CLIENT_CREATE',
    READ: 'CLIENT_READ',
    UPDATE: 'CLIENT_UPDATE',
    DELETE: 'CLIENT_DELETE',
  },
  USER: {
    CREATE: 'USER_CREATE',
    READ: 'USER_READ',
    UPDATE: 'USER_UPDATE',
    DELETE: 'USER_DELETE',
  },
};

export const ROL_PERMISSIONS = {
  [PERMISSION_TYPES.CLIENT]: [
    PERMISSIONS.SCHEDULE.READ,
    PERMISSIONS.REQUEST.CREATE,
    PERMISSIONS.REQUEST.READ,
    PERMISSIONS.REQUEST.UPDATE,
    PERMISSIONS.REQUEST.DELETE,
  ],
  [PERMISSION_TYPES.F_ADMIN]: [
    PERMISSIONS.SCHEDULE.READ,
    PERMISSIONS.REQUEST.READ,
    PERMISSIONS.REQUEST.FILTER,
    PERMISSIONS.VEHICLE.CREATE,
    PERMISSIONS.VEHICLE.READ,
    PERMISSIONS.VEHICLE.UPDATE,
    PERMISSIONS.VEHICLE.DELETE,
    PERMISSIONS.DRIVER.CREATE,
    PERMISSIONS.DRIVER.READ,
    PERMISSIONS.DRIVER.UPDATE,
    PERMISSIONS.DRIVER.DELETE,
    PERMISSIONS.CLIENT.CREATE,
    PERMISSIONS.CLIENT.READ,
    PERMISSIONS.CLIENT.UPDATE,
    PERMISSIONS.CLIENT.DELETE,
    PERMISSIONS.USER.CREATE,
    PERMISSIONS.USER.READ,
    PERMISSIONS.USER.UPDATE,
    PERMISSIONS.USER.DELETE,
  ],
  [PERMISSION_TYPES.F_READER]: [PERMISSIONS.SCHEDULE.READ, PERMISSIONS.REQUEST.READ, PERMISSIONS.REQUEST.FILTER],
  [PERMISSION_TYPES.F_SUPERVISOR]: [
    PERMISSIONS.SCHEDULE.CREATE,
    PERMISSIONS.SCHEDULE.READ,
    PERMISSIONS.SCHEDULE.UPDATE,
    PERMISSIONS.SCHEDULE.DELETE,
    PERMISSIONS.REQUEST.READ,
    PERMISSIONS.REQUEST.FILTER,
  ],
};
