export const VEHICLE_DRIVER_LIST_TABLE_HEADERS_IDS = {
  OPTIONS: 'vehicleDriver-options',
  NAME: 'Name',
  RUT: 'RUT',
  PATENT: 'Patent',
  REQUEST_STATE: 'RequestState',
};

export const VEHICLE_DRIVER_TABLE_HEADERS = [
  VEHICLE_DRIVER_LIST_TABLE_HEADERS_IDS.OPTIONS,
  VEHICLE_DRIVER_LIST_TABLE_HEADERS_IDS.NAME,
  VEHICLE_DRIVER_LIST_TABLE_HEADERS_IDS.RUT,
  VEHICLE_DRIVER_LIST_TABLE_HEADERS_IDS.PATENT,
  VEHICLE_DRIVER_LIST_TABLE_HEADERS_IDS.REQUEST_STATE,
];
