export const REQUEST_LIST_TABLE_HEADERS_IDS = {
  OPTIONS: 'request-options',
  // Client
  CLIENT_NAME: 'ClientName',
  // Request
  REQUEST_STATE: 'RequestState',
  VALIDITY_START: 'ValidityStart',
  VALIDITY_END: 'ValidityEnd',
  VALIDITY_START_HOUR: 'ValidityStartHour',
  VALIDITY_END_HOUR: 'ValidityEndHour',
  // Driver
  FULL_NAME: 'FullName',
  RUT: 'RUT',
  // Vehicle
  PATENT: 'Patent',
  // Auth
  MODIFIED: 'Modified',
  MODIFIED_BY: 'ModifiedBy',
};

export const REQUEST_LIST_TABLE_DEF_HEADERS = [
  REQUEST_LIST_TABLE_HEADERS_IDS.OPTIONS,
  REQUEST_LIST_TABLE_HEADERS_IDS.CLIENT_NAME,
  REQUEST_LIST_TABLE_HEADERS_IDS.PATENT,
  REQUEST_LIST_TABLE_HEADERS_IDS.RUT,
  REQUEST_LIST_TABLE_HEADERS_IDS.FULL_NAME,
  REQUEST_LIST_TABLE_HEADERS_IDS.VALIDITY_START,
  REQUEST_LIST_TABLE_HEADERS_IDS.VALIDITY_END,
  REQUEST_LIST_TABLE_HEADERS_IDS.VALIDITY_START_HOUR,
  REQUEST_LIST_TABLE_HEADERS_IDS.VALIDITY_END_HOUR,
  REQUEST_LIST_TABLE_HEADERS_IDS.REQUEST_STATE,
  REQUEST_LIST_TABLE_HEADERS_IDS.MODIFIED,
  REQUEST_LIST_TABLE_HEADERS_IDS.MODIFIED_BY,
];

export const REQUEST_LIST_TABLE_HEADERS: string[] = [
  'EMPTY',
  'REQUEST_NEW.REQUEST_BASIC_DATA.CLIENT_NAME',
  'VEHICLES.PATENT',
  'DRIVERS.NAME',
  'DRIVERS.RUT',
  'REQUESTS.VALIDITY_START',
  'REQUESTS.VALIDITY_END',
  'REQUESTS.VALIDITY_START_HOUR',
  'REQUESTS.VALIDITY_END_HOUR',
  'REQUESTS.REQUEST_STATE.TITLE',
  'REQUESTS.MODIFIED_BY',
  'REQUESTS.MODIFIED',
];
